web:
    build: ./jenkinsmeta-web
    command: python -m SimpleHTTPServer 80
    ports:
        - "80:80"
    links:
        - server

server:
    build: ./jenkinsmeta-server
    command: python -m SimpleHTTPServer 9000
    ports:
        - "8000:8000"
    links:
        - worker

worker:
    build: ./jenkinsmeta-server
    command: python -m SimpleHTTPServer 9000
    ports:
        - "9001:9001"
#    links:
#        - jenkins

#jenkins:
#    image: jenkins
#    ports:
#        - "8080:8080"
#        - "50000:50000"

